### ISSUE TITLE
[0.3.0] "Uncaught TypeError: Cannot read property 'feature' of undefined" after build. 

### ISSUE THREAD

**Issue by netfish88** [UDST/vizicities#176] opened 2016-09-19 09:28 UTC
hi. when I try to run the index.html on test folder, 
3D building doesn't appear on the screen although the base map is shown. 
In console, "Uncaught TypeError: Cannot read property 'feature' of undefined". 
on 47th line of GeoJSON.js. 

![image](https://cloud.githubusercontent.com/assets/11173194/18627544/79c6e4ec-7e96-11e6-865e-6b3c551711d1.png)

but strange thing is it works with vizicities.js file on dist folder at first, but it doesn't work after gulp build. 

![image](https://cloud.githubusercontent.com/assets/11173194/18627594/c9f5f8cc-7e96-11e6-9d3a-60a7d60d756e.png)

any hint for this problem ?

**Comment by robhawkes** [comment] 2016-10-03 15:14
Thanks for reporting this! I've confirmed the issue and have identified the cause. We have a PR with the fix (https://github.com/UDST/vizicities/pull/180) and hope to have this accepted and merged in shortly :)

**Comment by robhawkes** [comment] 2016-10-03 15:18
Ok, the fix is merged into `master` so you should be able to run `gulp build` and have a working version without the TopoJSON error now.

Let me know how you get on :)

**Closed by robhawkes** 2016-10-03 15:18 UTC
Labels: Priority: High, Status: Completed, Type: Maintenance
